version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendRECUC
    container_name: frontendRECUC
    ports:
      - "3000:3000"
    networks:
      - redwebRECUC

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendRECUC
    container_name: backendRECUC
    ports:
      - "8000:8000"
    networks:
      - redwebRECUC

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebRECUC
    container_name: webRECUC
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - redwebRECUC

networks:
  redwebRECUC:
    driver: bridge
